name: ✨ Feature request
description: Suggest an idea for this project.
title: "Title"
labels: ["type: enhancement", "status: todo"]
assignees:
  - alexis-gss
body:
  - type: textarea
    id: describe-the-context
    attributes:
      label: Describe the context
      description: A clear and concise description of what the problem is.
      placeholder: A clear and concise description of what the problem is.
    validations:
      required: true
  - type: textarea
    id: describe-solution-like
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: describe-alternatives-considered
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
  - type: textarea
    id: additional-ccontext
    attributes:
      label: Additional context
      description: Add any other context about the feature here.
      placeholder: Add any other context about the feature here.
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to complete this project improvement form !
